name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: run
      run: docker run -d --name docker -v `pwd`/files:/files docker /files/run.sh
    - name: docker push1
      run: docker push -d --name docker -v `pwd`/files:/files docker /files/run.sh
    
